### **내장 함수 zip**
- zip은 여러 배열을 튜플로 묶어주는 연산을 해준다.

#### < 1차원 리스트 >
- 다음과 같이 원소의 길이가 같은 1차원 배열(리스트)가 a, b가 있을 때, 동일한 위치에 있는 원소를 튜플로 묶어 리턴한다.
- iterable한 결과(zip 객체)로 리턴하므로 꼭 for문이나 iterator와 함께 사용되어야한다.

```python
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]

# list내 for 문
print([i for i in zip(a, b)])
#[(1, 6), (2, 7), (3, 8), (4, 9), (5, 0)]
```

```python
# 두 배열의 각 자리값끼리 곱한 값의 총합 구하기
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]
result = [i*j for i, j in zip(a, b)]
print("result : ", result, ", sum : ", sum(result))
#result :  [6, 14, 24, 36, 0],  sum :  80
```

### < 2차원 리스트 >
- 단일 for문은 단순히 요소만을 추가해준다.

```python
a = [[1, 2], [2, 3]]
b = [[3, 4], [5, 6]]
#단순 zip
print([i for i in zip(a, b)])
# result : [([1, 2], [3, 4]), ([2, 3], [5, 6])]
```
- 2차원 배열의 각 원소간 연산을 처리하기 위해서는 2중으로 for문이 필요하다

- **행렬의 덧셈**

```python
a = [[1, 2], [2, 3]]
b = [[3, 4], [5, 6]]
result = []
#각 자리 원소를 곱한 것들의 총 합
for i in range(len(a)):
    temp = [i * j for i, j in zip(a[i], b[i])]
    result.append(temp)
print("result : ", result)
# result :  [[3, 8], [10, 18]]
```

### Numpy module
- numpy 모듈에 multiply 함수를 이용해서 두 리스트 사이에 연산을 수행할 수 있다.

- add(), substract(), multiply(), divide()
- 각각 더하기, 빼기, 곱하기, 나누기를 수행할 수 있다.

- add()

```python
import numpy
a = numpy.array([1,2,3])
b = numpy.array([4,5,6])
print(a + b)  # print(numpy(a, b))
# [5 7 9]
```
- substract() 또는 마이너스 연산자  ' - '

```python
import numpy
a = numpy.array([1, 2, 3])
b = numpy.array([4, 5, 6])
print(numpy.subtract(a, b))  # print(a - b)
# [-3 -3 -3]
```

- multiply() 또는 곱하기 연산자 ' * '

```python
import numpy

a = numpy.array([1, 2, 3])
b = numpy.array([4, 5, 6])

print(numpy.multiply(a, b))  # print(a * b)
#[ 4 10 18]
```

- divide() 또는 나누기 연산자 ' / '

```python
import numpy

a = numpy.array([1, 2, 3])
b = numpy.array([4, 5, 6])

print(numpy.divide(a, b))  # print(a / b)
#[0.25 0.4  0.5 ]
```

### **내장 함수 map**

- 숫자형 문자열을 입력받을 때 주로 사용
- 리스트 연산으로도 사용
- map(function, iterable) 형태로, iterable에는 꼼마(,)로 여러개의 iterable 즉 튜플이나 리스트가 자리할 수 있다.

- < 1차원 list >

```python
# sort 함수의 key 옵션에 주로 사용한 예시 코드
# 리스트의 각 원소는 튜플 형태로, 이름과 나이를 가지고 있다고 가정
people = [('Alice', 30), ('Bob', 25), ('Charlie', 35)]
# 나이를 기준으로 정렬하기 위해 lambda 함수를 사용
sorted_people = sorted(people, key=lambda person: person[1])
# 결과 출력
print(sorted_people)
```

- lambda는 lambda <매개변수> : <반환하고자 하는 계산식> 형식으로 사용되고 주로 sort의 key 옵션으로 많이 사용된다.

```python
a = [1, 2, 3]
b = [4, 5, 6]
print(list(map(lambda x, y: x*y, a, b)))
#[4, 10, 18]
```
- 위 예시로는 x, y 두개의 변수를 받아서 x*y 연산을 수행하는 함수에  a, b 리스트를 넣음으로써 각 원소들을 돌며 연산을 수행한다.

- map 함수는 map 객체를 리턴하므로 리스트나 튜플로 변환하여 출력해야 한다.

- < 2차원 list >
- zip 함수 때와 마찬가지로 2차원 배열에서는 for문을 이용하여 각 리스트를 돌아가며 연산한다.

```python
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
result = []

for i in range(len(a)):
    result.append(list(map(lambda x, y: x*y, a[i], b[i])))

print(result)
#[[5, 12], [21, 32]]
```